"""TaxYearRules Protocol - one implementation per AY.

Adding AY 2027-28 = add new ay_2027_28.py exporting RULES. Zero edits elsewhere.
"""
from typing import Protocol
from app.domain.money import Money
from app.domain.enums import TaxRegime, RuleLifecycle


class TaxYearRules(Protocol):
    """One implementation per AY. New AY = new file."""
    assessment_year: str
    version: str
    lifecycle: RuleLifecycle
    governing_act: str  # "1961" or "2025"

    def slab_limits(self, regime: TaxRegime) -> list[int]: ...
    def slab_rates_bps(self, regime: TaxRegime) -> list[int]: ...
    def standard_deduction(self, regime: TaxRegime) -> Money: ...
    def rebate_87a_threshold(self, regime: TaxRegime) -> Money: ...
    def rebate_87a_amount(self, regime: TaxRegime) -> Money: ...
    def sec_80c_limit(self, regime: TaxRegime) -> Money: ...
    def sec_80ccd_1b_limit(self, regime: TaxRegime) -> Money: ...
    def sec_80d_limit(self, regime: TaxRegime, senior: bool) -> Money: ...
    def sec_24b_cap(self) -> Money: ...
    def sec_80tta_limit(self) -> Money: ...
    def sec_111a_rate_bps(self) -> int: ...
    def sec_112a_rate_bps(self) -> int: ...
    def sec_112a_exemption(self) -> Money: ...
    def cii_for(self, fy: str) -> int: ...
    def sec_44ad_turnover_limit(self) -> Money: ...
    def sec_44ad_rate_bps(self, is_cash: bool) -> int: ...
    def sec_44ada_turnover_limit(self) -> Money: ...
    def sec_44ada_rate_bps(self) -> int: ...
    def vda_rate_bps(self) -> int: ...
    def vda_no_loss_setoff(self) -> bool: ...
    def allowed_itr_forms(self, profile: dict) -> list[str]: ...
    def new_regime_allowed_deductions(self) -> set[str]: ...
    def sec_10_exemptions(self) -> dict[str, str]: ...
