/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        navy:          '#0B1929',
        'navy-mid':    '#112236',
        'navy-light':  '#1A3150',
        gold:          '#C9943A',
        'gold-light':  '#E8B86D',
        'gold-pale':   '#FDF3E0',
        'accent-blue': '#1D6FA4',
        'accent-teal': '#0F766E',
        'accent-rose': '#BE185D',
        success:       '#15803D',
        'success-bg':  '#DCFCE7',
        warning:       '#B45309',
        'warning-bg':  '#FEF3C7',
        danger:        '#B91C1C',
        'danger-bg':   '#FEE2E2',
        info:          '#1E40AF',
        'info-bg':     '#DBEAFE',
        bg:            '#F4F6F9',
        'bg-card':     '#FFFFFF',
        border:        '#E1E7EF',
        'border-strong':'#C8D3E0',
        'text-primary': '#0F1E2D',
        'text-secondary':'#4A5D72',
        'text-muted':  '#8A9BB0',
      },
      fontFamily: {
        serif:  ['"Crimson Pro"', 'serif'],
        sans:   ['"DM Sans"', 'sans-serif'],
        mono:   ['"DM Mono"', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '10px',
        sm: '6px',
      },
      width: { sidebar: '258px' },
      height: { topbar: '62px' },
    },
  },
  plugins: [],
}
